services:
  spelling-bee-web:
    container_name: spelling-bee-solver
    build: .
    ports:
      - "8060:8080"
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    init: true
