services:
  spelling-bee-solver:
    container_name: spelling-bee-solver
    build: 
      context: .
      dockerfile: Dockerfile.slim
    ports:
      - "8060:8080"
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    init: true
